export const duelCopy = {
  en: {
    duelBack: "Back",
    duelProUnlimited: "PRO: UNLIMITED",
    duelFreeLeft: "{left}/20 Q LEFT",
    duelCustomArena: "CUSTOM ARENA",
    duelTitle: "DUEL",
    duelDescription:
      "Dial in the room. 2–10 players. 1–100 questions. Same paper, live seats, fastest high score wins.",
    duelBuildMatch: "▚ BUILD THE MATCH",
    duelSubject: "SUBJECT",
    duelPlayers: "PLAYERS",
    duelQuestions: "QUESTIONS",
    duelUnitP: "P",
    duelUnitQ: "Q",
    duelTildeMin: "~{n} min",
    duelStarting: "STARTING...",
    duelStart: "START · {players}P · {questions}Q",
    duelFreeLimit: "FREE LIMIT REACHED · UNLOCK PRO (200 ETB)",
    duelJoinWithCode: "JOIN WITH DUEL CODE",
    duelEnterCode: "ENTER CODE",
    duelEnter: "ENTER",
    duelLog: "DUEL LOG (",
    duelLogMeta: "{a}/{b}P · {c}Q · {code}",
    duelVictory: "VICTORY",
    duelDefeat: "DEFEAT",
    duelDraw: "DRAW",
    duelPlayNow: "PLAY NOW ▶",
    duelWaiting: "WAITING",
    duelNoDuels: "NO DUELS RECORDED YET.",
    duelNoDuelsHint: "Dial a room above and drop the code in your study group.",
    duelCreateFailed: "Failed to create Duel",

    duelCouldNotJoin: "Could not join",
    duelError: "ERROR",
    duelNotFound: "DUEL NOT FOUND",
    duelNotFoundBody: 'The code "{code}" does not exist or has expired.',
    duelBackToLobby: "BACK TO LOBBY",
    duelAbort: "ABORT",
    duelCombo: "COMBO",
    duelInstantFeedbackAria: "Instant feedback",
    duelModeLive: "LIVE",
    duelModeExam: "EXAM",
    duelQuestionNavAria: "Question navigation",
    duelQuestionN: "Question {n}",
    duelPostingScore: "POSTING SCORE...",
    duelLockIn: "LOCK IN SCORE",
    duelNextQuestion: "NEXT QUESTION ▶",
    duelLobby: "Lobby",
    duelLobbyLive: "{a}/{b} LIVE",
    duelHeaderMeta: "{count}Q · {min} MIN",
    duelArenaTitle: "{n}P ARENA",
    duelCode: "DUEL CODE",
    duelShareHint: "SHARE THIS — SEATS FILL LIVE",
    duelMatchConcluded: "MATCH CONCLUDED",
    duelWinner: "{name} TAKES THE CROWN!",
    duelHonorableDraw: "HONORABLE DRAW!",
    duelFirstPlaceXp: "First place awarded +50 XP on the track leaderboard.",
    duelCabinetHot: "YOUR CABINET IS HOT",
    duelStartBody:
      "{questions} questions. {minutes} minute clock. Same paper as everyone in the room. Score and speed decide rank.",
    duelStartButton: "START ▶ ({n} Q)",
    duelLobbyFull: "LOBBY FULL",
    duelJoiningRoom: "JOINING ROOM",
    duelLobbyFullBody: "Every seat is taken. Watch the board or start your own room.",
    duelClaiming: "Claiming an open cabinet...",
    duelScorePosted: "SCORE POSTED",
    duelFinished: "{a}/{b} FINISHED",
    duelKeepRoom:
      "Keep the room open. Rivals can still take empty seats and the crown can still move.",
    duelPullMore: "PULL MORE PLAYERS",
    duelShareTelegram: "SHARE TO TELEGRAM",
    duelCopied: "COPIED",
    duelCopy: "COPY",

    duelDecrease: "Decrease {label}",
    duelIncrease: "Increase {label}",

    duelSeatsAria: "Duel seats",
    duelHost: "HOST",
    duelSeatP: "P{n}",
    duelSeatYou: " · YOU",
    duelSeatOpen: "OPEN",
    duelSeatRank: "RANK {n}",
    duelSeatDone: "DONE",
    duelSeatTime: " · {n}S",
    duelSeatReady: "READY",
    duelSeatInsert: "INSERT PLAYER",
  },
  am: {
    duelBack: "ተመለስ",
    duelProUnlimited: "ፕሮ፡ ያልተገደበ",
    duelFreeLeft: "{left}/20 ጥያቄ ቀርቷል",
    duelCustomArena: "የራስ ሜዳ",
    duelTitle: "ዱኤል",
    duelDescription:
      "ክፍሉን ያዘጋጁ። 2–10 ተጫዋቾች። 1–100 ጥያቄዎች። አንድ ወረቀት፣ ቀጥታ መቀመጫዎች፣ ፈጣኑ ከፍተኛ ውጤት ያሸንፋል።",
    duelBuildMatch: "▚ ግጥሚያውን ገንባ",
    duelSubject: "ርህቅ",
    duelPlayers: "ተጫዋቾች",
    duelQuestions: "ጥያቄዎች",
    duelUnitP: "ተ",
    duelUnitQ: "ጥ",
    duelTildeMin: "~{n} ደቂቃ",
    duelStarting: "በመጀመር ላይ...",
    duelStart: "ጀምር · {players}P · {questions}Q",
    duelFreeLimit: "ነፃ ገደብ ሞሏል · ፕሮ ይክፈቱ (200 ብር)",
    duelJoinWithCode: "በዱኤል ኮድ ይቀላቀሉ",
    duelEnterCode: "ኮድ ያስገቡ",
    duelEnter: "አስገባ",
    duelLog: "የዱኤል መዝገብ (",
    duelLogMeta: "{a}/{b}P · {c}Q · {code}",
    duelVictory: "ድል",
    duelDefeat: "ሽንፈት",
    duelDraw: "እኩል",
    duelPlayNow: "አሁን ተጫወት ▶",
    duelWaiting: "በመጠበቅ ላይ",
    duelNoDuels: "እስካሁን ዱኤል አልተመዘገበም።",
    duelNoDuelsHint: "ከላይ ክፍል ያዘጋጁ እና ኮዱን በጥናት ቡድንዎ ያጋሩ።",
    duelCreateFailed: "ዱኤል መፍጠር አልተሳካም",

    duelCouldNotJoin: "መቀላቀል አልተቻለም",
    duelError: "ስህተት",
    duelNotFound: "ዱኤል አልተገኘም",
    duelNotFoundBody: 'ኮድ "{code}" አይገኝም ወይም ጊዜው አልቋል።',
    duelBackToLobby: "ወደ ሎቢ ተመለስ",
    duelAbort: "አቁም",
    duelCombo: "ኮምቦ",
    duelInstantFeedbackAria: "ፈጣን ግምገማ",
    duelModeLive: "ቀጥታ",
    duelModeExam: "ፈተና",
    duelQuestionNavAria: "የጥያቄ አሰሳ",
    duelQuestionN: "ጥያቄ {n}",
    duelPostingScore: "ውጤት በመላክ ላይ...",
    duelLockIn: "ውጤት አስቀምጥ",
    duelNextQuestion: "ቀጣይ ጥያቄ ▶",
    duelLobby: "ሎቢ",
    duelLobbyLive: "{a}/{b} ቀጥታ",
    duelHeaderMeta: "{count}ጥ · {min} ደቂቃ",
    duelArenaTitle: "{n}ተ ሜዳ",
    duelCode: "የዱኤል ኮድ",
    duelShareHint: "ይህን ያጋሩ — መቀመጫዎች በቀጥታ ይሞላሉ",
    duelMatchConcluded: "ግጥሚያው ተጠናቅቋል",
    duelWinner: "{name} ዘውዱን ወሰደ!",
    duelHonorableDraw: "እኩል ውጤት!",
    duelFirstPlaceXp: "አንደኛ ደረጃ +50 ነጥብ በክፍል ደረጃ ሰሌዳ ተሰጥቷል።",
    duelCabinetHot: "ካቢኔዎ ዝግጁ ነው",
    duelStartBody:
      "{questions} ጥያቄዎች። {minutes} ደቂቃ ሰዓት። ከሁሉም ሰው ጋር ተመሳሳይ ወረቀት። ውጤት እና ፍጥነት ደረጃውን ይወስናሉ።",
    duelStartButton: "ጀምር ▶ ({n} ጥ)",
    duelLobbyFull: "ሎቢ ሙሉ ነው",
    duelJoiningRoom: "ወደ ክፍል በመቀላቀል ላይ",
    duelLobbyFullBody: "ሁሉም መቀመጫ ተይዟል። ሰሌዳውን ይመልከቱ ወይም የራስዎን ክፍል ይጀምሩ።",
    duelClaiming: "ክፍት ካቢኔ በመያዝ ላይ...",
    duelScorePosted: "ውጤት ተለጠፈ",
    duelFinished: "{a}/{b} ጨርሷል",
    duelKeepRoom:
      "ክፍሉን ክፍት ያቆዩ። ተፎካካሪዎች አሁንም ክፍት መቀመጫ ይይዛሉ እና ዘውዱ ሊቀየር ይችላል።",
    duelPullMore: "ተጨማሪ ተጫዋቾች ይጎትቱ",
    duelShareTelegram: "በቴሌግራም ያጋሩ",
    duelCopied: "ተቀድቷል",
    duelCopy: "ቅዳ",

    duelDecrease: "{label} ቀንስ",
    duelIncrease: "{label} ጨምር",

    duelSeatsAria: "የዱኤል መቀመጫዎች",
    duelHost: "አስተናጋጅ",
    duelSeatP: "ተ{n}",
    duelSeatYou: " · እርስዎ",
    duelSeatOpen: "ክፍት",
    duelSeatRank: "ደረጃ {n}",
    duelSeatDone: "ተጠናቅቋል",
    duelSeatTime: " · {n}ሰ",
    duelSeatReady: "ዝግጁ",
    duelSeatInsert: "ተጫዋች ያስገቡ",
  },
};
