export const examCopy = {
  en: {
    examMistakesLockedKicker: "PRO FEATURE LOCKED",
    examMistakeBankDrill: "MISTAKE BANK DRILL",
    examMistakeDrillDesc:
      "Retrying your missed questions is reserved for Pro members. Unlock unlimited drills and pass with confidence.",
    examGoPro: "INSERT COIN — GO PRO (200 ETB)",
    examViewMistakesList: "VIEW MISTAKES LIST",
    examQuotaCompleted: "20 / 20 QUESTIONS COMPLETED",
    examQuotaModalBody:
      "You've used all 20 of your free daily questions (mocks and Duel rooms share this cap). Upgrade to Pro for unlimited mock papers, full 100-question sittings, and every track.",
    examDailyLimitKicker: "DAILY FREE LIMIT REACHED",
    examQuotaUsed: "20 / 20 QUESTIONS USED",
    examQuotaBody:
      "You've completed your daily allowance of 20 free questions. Pro unlocks unlimited questions, full 100-question papers, and every track.",
    examBackToArcade: "BACK TO ARCADE",
    examStageClear: "Stage clear",
    examGameOver: "Game over",
    examComboBonus: "(+{n} COMBO)",
    examMaxCombo: "MAX x{n}",
    examExit: "EXIT",
    examNoTimer: "NO TIMER",
    examCombo: "COMBO",
    examInstantLive: "LIVE",
    examInstantExam: "EXAM",
    examQuestionNav: "Question navigation",
    examQuestionTitle: "Question {n}",
    examFreePlanSubmitAfter: "Free plan — submit after Q{n}",
    examFinish: "Finish",
    examFinishQ: "Finish ({n} Q)",
    examCloseSourcePicker: "Close source picker",
    examFullSitting: "FULL SITTING",
    examLoadingPapers: "Loading papers…",
    examBack: "Back",
    examClose: "Close",
    examPastQuickMeta: "{n} Q · NO TIMER",
    examPastExamMeta: "{n} Q · {m} MIN",
  },
  am: {
    examMistakesLockedKicker: "የፕሮ ባህሪ ተቆልፏል",
    examMistakeBankDrill: "የስህተት ባንክ ልምምድ",
    examMistakeDrillDesc:
      "የተሳሳቷቸውን ጥያቄዎች መመለስ ለፕሮ ተጠቃሚዎች ብቻ ነው። ያልተገደበ ልምምድ ይክፈቱ እና በእምነት ያሳልፉ።",
    examGoPro: "ፕሮ ይክፈቱ (200 ብር)",
    examViewMistakesList: "የስህተት ዝርዝር ይመልከቱ",
    examQuotaCompleted: "20 / 20 ጥያቄ ተጠናቅቋል",
    examQuotaModalBody:
      "ሁሉንም 20 ነፃ የቀን ጥያቄዎችዎን ተጠቅመዋል (የመውጫ ፈተናዎች እና የዱኤል ክፍሎች ይህን ገደብ ይጋራሉ)። ያልተገደበ ፈተና፣ ሙሉ 100 ጥያቄ ፈተና እና ሁሉንም ክፍሎች ለማግኘት ወደ ፕሮ ያሳድጉ።",
    examDailyLimitKicker: "የቀን ነፃ ገደብ ሞሏል",
    examQuotaUsed: "20 / 20 ጥያቄ ተጠቅመዋል",
    examQuotaBody:
      "የዕለቱን 20 ነፃ ጥያቄ ገደብ ጨርሰዋል። የመውጫ ዕቅድ ፕሮ ያልተገደበ ጥያቄ፣ ሙሉ 100 ጥያቄ ፈተና እና ሁሉንም ክፍሎች ይከፍታል።",
    examBackToArcade: "ወደ መነሻ ተመለስ",
    examStageClear: "ደረጃ ተጠናቅቋል",
    examGameOver: "ጨዋታ አልቋል",
    examComboBonus: "(+{n} ኮምቦ)",
    examMaxCombo: "ከፍተኛ x{n}",
    examExit: "ውጣ",
    examNoTimer: "ሰዓት የለም",
    examCombo: "ኮምቦ",
    examInstantLive: "ቀጥታ",
    examInstantExam: "ፈተና",
    examQuestionNav: "የጥያቄ አሰሳ",
    examQuestionTitle: "ጥያቄ {n}",
    examFreePlanSubmitAfter: "ነፃ እቅድ — ከQ{n} በኋላ አስገባ",
    examFinish: "ጨርስ",
    examFinishQ: "ጨርስ ({n} ጥያቄ)",
    examCloseSourcePicker: "የምንጭ መራጩን ዝጋ",
    examFullSitting: "ሙሉ ፈተና",
    examLoadingPapers: "ወረቀቶች በመጫን ላይ…",
    examBack: "ተመለስ",
    examClose: "ዝጋ",
    examPastQuickMeta: "{n} ጥያቄ · ሰዓት የለም",
    examPastExamMeta: "{n} ጥያቄ · {m} ደቂቃ",
  },
};
