export const marksCopy = {
  en: {
    marksTitle: "PROJECTED TOTAL",
    marksBlurb:
      "Your newest mark per subject. Sitting a full mock paper updates that subject automatically.",
    marksOutOf: "out of {max}",
    marksNoneYet: "NOT SAT YET",
    marksFromMock: "FROM MOCK",
    marksManual: "ENTERED",
    marksEmpty: "No marks recorded yet.",
    marksEmptyDesc:
      "Sit a full mock paper in a subject, or type in a result from a paper you sat elsewhere.",
    marksMockOnly: "Only full mock papers update your total.",
    marksAddResult: "ADD A RESULT",
    marksAddTitle: "ADD A RESULT",
    marksScoreLabel: "Score",
    marksOutOfLabel: "out of",
    marksLabelPlaceholder: "Paper name (optional)",
    marksSave: "SAVE",
    marksCancel: "CANCEL",
    marksManualDisabled: "Adding results by hand is turned off.",
    marksDelete: "REMOVE",
    marksRemoved: "REMOVED",
    marksEntryAdded: "RESULT SAVED",
  },
  am: {
    marksTitle: "የተገመተ ጠቅላላ",
    marksBlurb:
      "በክፍል የቅርብ ውጤትዎ። ሙሉ ሞዴል ፈተና ሲያሳልፍ ይህ ክፍል በራስ-ሰር ይዘምናል።",
    marksOutOf: "ከ{max} ውስጥ",
    marksNoneYet: "ገና አልተሳለፈም",
    marksFromMock: "ከሞዴል",
    marksManual: "በእጅ የተመዘገበ",
    marksEmpty: "እስካሁን የተመዘገበ ውጤት የለም።",
    marksEmptyDesc:
      "በክፍል ውስጥ ሙሉ ሞዴል ፈተና ይቀምጡ፣ ወይም ከውጭ የሳሉትን ውጤት ይጨምሩ።",
    marksMockOnly: "ሙሉ ሞዴል ፈተና ብቻ ጠቅላላዎን ይዘምናል።",
    marksAddResult: "ውጤት ይጨምሩ",
    marksAddTitle: "ውጤት ይጨምሩ",
    marksScoreLabel: "ውጤት",
    marksOutOfLabel: "ከ",
    marksLabelPlaceholder: "የፈተናው ስም (አማራጭ)",
    marksSave: "አስቀምጥ",
    marksCancel: "ተው",
    marksManualDisabled: "በእጅ ውጤት ማስገባት ተዘግቷል።",
    marksDelete: "አስወግድ",
    marksRemoved: "ተወግዷል",
    marksEntryAdded: "ውጤቱ ተቀምጧል",
  },
};