export const progressCopy = {
  en: {
    progBack: "Back",
    subjectLabel: "Subject",
    subjectEmptyForTrack: "No published subjects in your track yet.",
    progErrorLog: "ERROR LOG",
    progMistakeBank: "MISTAKE BANK",
    progMistakeBankBlurb:
      "Every question you got wrong is logged here. Review and master your weak spots.",
    progTotalLogged: "TOTAL LOGGED",
    progUnresolved: "UNRESOLVED",
    progMastered: "MASTERED",
    progDrillMode: "MISTAKE DRILL MODE",
    progDrillProDesc:
      "Sit a personalized 20-question quiz generated exclusively from your failed questions.",
    progDrillLockedDesc: "Drilling your mistake bank as a quiz requires Pro access.",
    progStartDrill: "START MISTAKE DRILL ({n} Q)",
    progNoUnresolved: "NO UNRESOLVED MISTAKES IN THIS SUBJECT!",
    progUnlockQuiz: "UNLOCK MISTAKE QUIZ · GO PRO (200 ETB)",
    progProVaultLocked: "▚ PRO VAULT LOCKED",
    progHistoryLocked: "MISTAKE BANK HISTORY LOCKED",
    progHistoryLockedDesc:
      "Question-by-question mistake history, correct answer explanations, and personalized retry quizzes are reserved for Pro members.",
    progInsertCoinMistakes: "INSERT COIN — UNLOCK MISTAKES (200 ETB)",
    progReturnArcade: "RETURN TO ARCADE",
    progVaultCount: "MISTAKE VAULT ({n})",
    progMissedCount: "MISSED {n}x",
    progExplanation: "EXPLANATION: ",
    progNoRecorded: "NO RECORDED MISTAKES YET.",
    progNoRecordedDesc:
      "Complete mocks or drills. Any wrong answers will be logged here automatically.",
    progExamsSuffix: "exams",
    progTop50: "TOP 50",
    progStreakUnit: "d",
    progOperator: "OPERATOR",
    progYou: "YOU",
    progSecondsUnit: "s",
    progNoSittings: "NO SITTINGS YET. START A MOCK.",
    progProUnlimited: "PRO: UNLIMITED",
    progQuestionsToday: "{left}/20 QUESTIONS TODAY",
    progSelectStage: "SELECT STAGE",
    progFreeCap: " · 20 Q FREE CAP",
    progMinSuffix: " MIN · ",
    progQSuffix: " Q",
    progMissingAttempt: "MISSING ATTEMPT.",
    progReplay: "REPLAY",
    progCorrect: "Correct",
    progIncorrect: "Incorrect",
  },
  am: {
    progBack: "ተመለስ",
    subjectLabel: "ርህቅ",
    subjectEmptyForTrack: "በመንገድዎ ውስጥ የታተመ ርህቅ የለም።",
    progErrorLog: "የስህተት መዝገብ",
    progMistakeBank: "የስህተት ባንክ",
    progMistakeBankBlurb:
      "የተሳሳቱባቸው ጥያቄዎች በሙሉ እዚህ ይመዘገባሉ። ደካማ ቦታዎችዎን ይገምግሙ እና ይማሩ።",
    progTotalLogged: "ጠቅላላ የተመዘገበ",
    progUnresolved: "ያልተፈታ",
    progMastered: "የተካነ",
    progDrillMode: "የስህተት ልምምድ ሁነታ",
    progDrillProDesc:
      "ለእርስዎ ብቻ ከተሳሳቷቸው ጥያቄዎች የተዘጋጀ የ20 ጥያቄ ፈተና ይቀመጡ።",
    progDrillLockedDesc: "የስህተት ባንክዎን እንደ ፈተና መለማመድ የፕሮ መዳረሻ ይፈልጋል።",
    progStartDrill: "የስህተት ልምምድ ጀምር ({n} ጥያቄ)",
    progNoUnresolved: "በዚህ ክፍል ያልተፈታ ስህተት የለም!",
    progUnlockQuiz: "የስህተት ፈተና ይክፈቱ · ፕሮ ይሁኑ (200 ብር)",
    progProVaultLocked: "▚ የፕሮ ማከማቻ ተቆልፏል",
    progHistoryLocked: "የስህተት ባንክ ታሪክ ተቆልፏል",
    progHistoryLockedDesc:
      "ጥያቄ በጥያቄ የስህተት ታሪክ፣ የትክክለኛ መልስ ማብራሪያ እና ለእርስዎ የተዘጋጁ ድጋሚ ፈተናዎች ለፕሮ አባላት የተመደቡ ናቸው።",
    progInsertCoinMistakes: "ክፍያ ያድርጉ — ስህተቶችን ይክፈቱ (200 ብር)",
    progReturnArcade: "ወደ መነሻ ተመለስ",
    progVaultCount: "የስህተት ማከማቻ ({n})",
    progMissedCount: "ተሳሳተ {n}x",
    progExplanation: "ማብራሪያ: ",
    progNoRecorded: "እስካሁን የተመዘገበ ስህተት የለም።",
    progNoRecordedDesc:
      "የመውጫ ፈተናዎችን ወይም ልምምዶችን ይጨርሱ። የተሳሳቱ መልሶች በራስ-ሰር እዚህ ይመዘገባሉ።",
    progExamsSuffix: "ፈተና",
    progTop50: "ምርጥ 50",
    progStreakUnit: "ቀ",
    progOperator: "ተጫዋች",
    progYou: "እርስዎ",
    progSecondsUnit: "ሰ",
    progNoSittings: "እስካሁን ፈተና አልተቀመጡም። የመውጫ ፈተና ይጀምሩ።",
    progProUnlimited: "ፕሮ፡ ያልተገደበ",
    progQuestionsToday: "{left}/20 ጥያቄዎች ዛሬ",
    progSelectStage: "ደረጃ ይምረጡ",
    progFreeCap: " · 20 ጥያቄ ነፃ ገደብ",
    progMinSuffix: " ደቂቃ · ",
    progQSuffix: " ጥያቄ",
    progMissingAttempt: "ፈተና አልተገኘም።",
    progReplay: "ድጋሚ ግምገማ",
    progCorrect: "ትክክል",
    progIncorrect: "ስህተት",
  },
};
