import { shellCopy } from "./copy/shell";
import { onboardingCopy } from "./copy/onboarding";
import { homeCopy } from "./copy/home";
import { examCopy } from "./copy/exam";
import { duelCopy } from "./copy/duel";
import { progressCopy } from "./copy/progress";
import { proCopy } from "./copy/pro";
import { marksCopy } from "./copy/marks";

const baseCopy = {
  en: {
    brand: "MatricPrep",
    selam: "Selam",
    student: "student",
    home: "Home",
    practice: "Practice",
    exams: "Exams",
    history: "History",
    pro: "Pro",
    account: "Account",
    continueMock: "Continue exam",
    quickDrill: "Quick 10",
    sourcePick: "Choose where questions come from.",
    sourceMock: "Mock exam",
    sourceMockHint: "Models from universities",
    sourceMockCount: "{n} questions from university model papers",
    sourceMockEmpty: "No mock exams in this subject yet",
    sourcePast: "Past national papers",
    sourcePastHint: "{n} national papers · pick a year",
    sourcePastEmpty: "No past papers in this subject yet",
    sourcePastKicker: "Past national papers",
    sourcePastTitle: "Pick a year",
    sourcePastBody: "Official national papers, labeled by year. You take that sitting.",
    sourceBlurbQuick:
      "Choose a paper source. Ten questions, no clock — finish when you are ready.",
    sourceBlurbExam:
      "Mock exams mix university model papers. Past national papers are official national sittings.",
    questionBank: "Question bank",
    sourceMockSub: "University models",
    sourcePastSub: "National papers",
    sourceAll: "All random",
    sourceAllHint: "Mixed mock and past papers",
    sourceAllCount: "{n} questions from every paper",
    sourceAllEmpty: "No questions in this subject yet",
    sourceNeedPick: "Choose a mock or a past paper first",
    countPickKicker: "Sitting size",
    countPickTitle: "How many questions?",
    countPickBody: "Pick a set. You will not sit the whole paper at once.",
    countPickGoal: "Your daily goal",
    countPickQs: "{n} questions",
    countPickTime: "About {n} min",
    countPickTooFew: "This paper has {n} questions",
    countPickAll: "All {n} on this paper",
    practiceMockHint: "{n} university model questions",
    tracks: "Tracks",
    pickTrack: "Choose your track",
    trackLocked: "Track is locked on the free plan.",
    changeTrackPro: "Change with Pro",
    streak: "Streak",
    xp: "XP",
    free: "Free",
    proActive: "Pro active",
    upgrade: "Unlock the full season",
    onboardingTitle: "Set up your study hall",
    language: "Language",
    theme: "Theme",
    accent: "Accent",
    fontSize: "Text size",
    dailyGoal: "Daily question goal",
    haptics: "Haptics",
    sound: "Sounds",
    instant: "Instant feedback",
    motion: "Reduce motion",
    university: "University",
    year: "Year of study",
    examYear: "Target exam year",
    save: "Save preferences",
    next: "Continue",
    finish: "Enter the hall",
    noQuestions: "No published questions yet.",
    review: "Review answers",
    backHome: "Back home",
    score: "Your score",
    pending: "Waiting for admin review",
    rejected: "Payment was rejected",
    submitPay: "Submit for approval",
    hallOfFame: "Hall of Fame",
    scoreboard: "Scoreboard",
    boardBlurbBiweekly: "This fortnight's winners in {track}. Ranked by XP earned in the window.",
    boardBlurbMonthly: "This month's winners in {track}. Ranked by XP earned since the 1st.",
    boardBlurbAll: "All-time ranking in {track}. Lifetime XP, then streak.",
    periodBiweekly: "2 weeks",
    periodMonthly: "Month",
    periodAllTime: "All-time",
    yourStanding: "Your standing",
    changeTrack: "Faculty",
    yourTrack: "Your major",
    noPeriodPlayers: "No scores this period yet. Sit a paper to claim the board.",
    noPlayers: "No players logged yet for this track.",
    unrankedPeriod: "Unranked this period",
    timeUp: "TIME UP",
    pencilsDown: "PENCILS DOWN",
    timeUpBody:
      "The clock hit zero. Answers you locked in still count. Blank items score as missed.",
    seeResults: "SEE RESULTS",
    posting: "POSTING SCORE…",
    seeMore: "SEE MORE",
    showMore: "SHOW MORE",
    redeemKicker: "Got a gift?",
    redeemTitle: "Redeem a code",
    redeemHint: "Enter a Pro gift code to claim it.",
    redeemPlaceholder: "GIFT CODE",
    redeemAction: "REDEEM",
    redeemEmpty: "Enter a gift code.",
    redeemSuccess: "Gift claimed. Pro is on.",
    redeemFailed: "Redeem failed.",
    redeemAlreadyPro: "You already have Pro.",
    redeemNotFound: "Gift code not found.",
    redeemOwnGift: "You cannot redeem your own gift.",
    redeemPending: "This gift is still being reviewed.",
    redeemClaimed: "This gift was already claimed.",
    redeemInvalid: "This gift is no longer valid.",
    saving: "Saving…",
    homeHudXp: "XP",
    homeHudLast: "LAST",
    homeBrand: "MATRIC PREP",
    homeQuick10: "QUICK 10",
    homeExam: "EXAM",
    homeDuel: "DUEL",
    homeMistakeBank: "MISTAKE BANK",
    homeLeaderboard: "LEADERBOARD",
    homeReview: "REVIEW",
    homePractice: "PRACTICE",
    homeNotes: "NOTES",
    homeSubNotes: "READ STUDY NOTES",
    notesKicker: "Notes",
    notesTitle: "Study notes",
    notesComingSoon: "Coming soon. Notes for every subject are on the way.",
    notesSoonBadge: "Coming soon",
    homeSub10NoTimer: "10 QUESTIONS · NO TIMER",
    homeSubTimed: "{n} QUESTIONS · TIMED",
    homeSubDuelFriends: "DUEL WITH FRIENDS",
    homeSubRetryWeak: "RETRY WEAKNESSES",
    homeSubRankings: "RANKINGS",
    homeSubLastScore: "LAST SCORE {n}%",
    homeSubNoSitting: "NO SITTING YET",
    homeSubBrowseBank: "BROWSE THE BANK",
    homeDailyLimit: "LIMIT REACHED",
    homeCreditPro: "CREDIT ∞",
    homeCreditFree: "CREDIT {left}/20 Q",
    homeUpgradeHint: "Daily limit reached — upgrade for unlimited play",
    restrictClose: "Maybe later",
    restrictUpgrade: "Upgrade to Pro",
    restrictPerk1: "Unlimited questions & full 100-question papers",
    restrictPerk2: "Duel rooms: 2–10 players, up to 100 questions",
    restrictPerk3: "Mistake Bank history & adaptive drills",
    restrictPerk4: "Every track & official blueprint weights",
    restrictPerk5: "One payment (200 ETB) · Active until season end",
    restrictQuestionsKicker: "FREE QUOTA EXHAUSTED",
    restrictQuestionsTitle: "20 / 20 QUESTIONS",
    restrictQuestionsBadge: "DAILY CAP REACHED",
    restrictQuestionsDesc:
      "Free accounts get 20 questions per day across mock exams and Duel rooms. Upgrade to Pro for unlimited mocks, full 100-question sittings, and every track.",
    restrictDuelsKicker: "FREE QUOTA EXHAUSTED",
    restrictDuelsTitle: "20 / 20 QUESTIONS",
    restrictDuelsBadge: "DAILY CAP REACHED",
    restrictDuelsDesc:
      "Duel questions share the same 20-question daily cap as mocks. Upgrade to Pro for rooms up to 10 players and 100-question papers.",
    restrictMistakesKicker: "PRO OPERATOR VAULT",
    restrictMistakesTitle: "MISTAKE BANK LOCKED",
    restrictMistakesBadge: "PRO FEATURE",
    restrictMistakesDesc:
      "Mistake Bank history and personalized weak-spot drills are reserved for Pro operators. Retrying failed questions is the fastest path to 70%+.",
    restrictProStageKicker: "STAGE LOCKED",
    restrictProStageTitle: "PRO EXAM SITTING",
    restrictProStageBadge: "PRO REQUIRED",
    restrictProStageDesc:
      "This official national exam sitting is exclusive to Pro members. Unlock every past year variant and full blueprint weights.",
    restrictGeneralKicker: "COIN OP · GO PRO",
    restrictGeneralTitle: "UNLOCK UNLIMITED PASS",
    restrictGeneralBadge: "SEASON PASS",
    restrictGeneralDesc:
      "Take full control of your preparation with unlimited questions, adaptive mistake drills, and Duel rooms.",
    homeSelectMode: "SELECT MODE",
    homeReady: "READY",
    homeStatsKicker: "STATS",
    homeStatsStreakBadge: "{n}D STREAK",
    homeStatsStreak: "STREAK",
    homeStatsDays: "DAYS",
    homeStatsGoal: "GOAL",
    homeStatsScore: "SCORE",
    homeStatsRecent: "RECENT SITTINGS",
    homeStatsAria: "Player statistics",
    homeStreakTooltip: "{n} day streak",
    homeCoinOp: "COIN OP",
    homeQuotaLeft: "{left} / {max} Q LEFT",
    homeQuotaEmpty: "0 LEFT",
    homeQuotaUsed: "{used} of {max} questions used today",
    homeQuotaDetails: "DETAILS",
    homeQuotaGoPro: "INSERT COIN, GO PRO",
    homeQuotaNoActivity: "No activity yet today",
    homeQuotaUsedSummary: "Used: {summary}",
    homeMarqueePro: "★ PRO ACTIVE ★",
    homeMarqueeCoin: "★ INSERT COIN ★",
    homeMarqueeQuestions: "{n} QUESTIONS",
    homeMarqueeRun: "{duration} RUN",
    homeMarqueeStreak: "STREAK {n} DAYS",
    homeMarqueeLuck: "GOOD LUCK {name}",
    homeDurationHours: "{h}h",
    homeDurationHoursMin: "{h}h {m}m",
    homeDurationMin: "{m} minutes",
    proPageKicker: "Pro",
    proInsertCoin: "INSERT COIN",
    proOnePayment: "One payment covers you until matric season end.",
    proSeasonEndsOn: "Pro stays active until {date} — the end of exam season.",
    proPayMethodLabel: "Choose how to pay",
    proPayTapToSelect: "Tap a payment method to see the number",
    proCopyNumber: "Copy number",
    proNumberCopied: "Number copied",
    proCheckoutPerk1: "Every track",
    proCheckoutPerk2: "Unlimited mock papers",
    proCheckoutPerk3: "Mistake Bank Quiz mode",
    proCheckoutPerk4: "Duel rooms (2–10 players)",
    proCheckoutPerk5: "Blueprint weights",
    proCheckoutPerk6: "Answer review forever",
    proPaymentHeading: "Payment",
    proScreenshotLabel: "Screenshot",
    proProcessing: "PROCESSING",
    proAttachScreenshot: "Please attach your payment screenshot.",
    proImageOnly: "Please upload an image file (screenshot or photo).",
    proImageMaxSize: "That image is too large (max 5 MB).",
    proUploadFailedMsg: "Upload failed. Please try again.",
    proSubmittedAdmin: "Submitted. An admin will review shortly.",
    proAccessUnlocked: "PRO ACCESS UNLOCKED",
    proUntilDate: "UNTIL {date}",
    proSeasonEndFallback: "season end",
    proMemberDesc:
      "Zero question caps. Official blueprint-weighted sittings and competitive modes ready.",
    proGiftKicker: "SEND PRO",
    proGiftTitle: "Gift a friend",
    proGiftAttach: "Attach the payment screenshot.",
    proGiftSubmitted: "Submitted. Code unlocks after review.",
    proGiftPayCopy: "Pay {price} ETB. After review you get a code to send.",
    proGiftOpenCode: "OPEN CODE",
    proGiftCopied: "COPIED",
    proGiftCopyBtn: "COPY",
    proGiftSendBtn: "SEND",
    proGiftSubmitBtn: "GIFT PRO · {price} ETB",
    proGiftReviewWait: "Payment in review. Code unlocks when approved.",
    proGiftClaimedBy: "{code} claimed by {name}",
    proUploadFailed: "Upload failed",
    proBenefitsSr: "Pro benefits",
    proStatusSr: "Pro status",
    proHeroExamTitle: "EXAM",
    proHeroExamKicker: "100 QUESTIONS",
    proHeroExamSub: "Timed sitting from mock exams or a past exit year",
    proHeroExamCta: "START EXAM",
    proHeroQuickTitle: "QUICK 10",
    proHeroQuickKicker: "RAPID SPRINT",
    proHeroQuickSub: "10-question burst anytime for fast practice",
    proHeroQuickCta: "PRACTICE",
    proHeroMistakesTitle: "MISTAKE BANK",
    proHeroMistakesKicker: "PRO VAULT",
    proHeroMistakesSub: "Drill all missed questions until 100% mastered",
    proHeroMistakesCta: "DRILL ERRORS",
    proHeroDuelTitle: "DUEL",
    proHeroDuelKicker: "LIVE ARENA",
    proHeroDuelSub: "Unlimited Duel rooms with friends, 2–10 players",
    proHeroDuelCta: "CHALLENGE",
    howItWorksTitle: "🚀 HOW IT WORKS",
    howItWorksSteps: [
      "1️⃣ Choose Your Track\nSelect your track when you get started and pick the subjects you want to practise. 🎓\n⭐ Pro users can change their track anytime.",
      "2️⃣ Practice or Take an Exam\n🧠 Quiz: Challenge yourself with a quick set of 10 questions.\n📝 Exam: Sit a full timed mock paper and test your preparation.",
      "3️⃣ Use the App & Compete\n📱 Open the app to access Timed Exams, Question History, Leaderboards, Duel with Friends, Notes, and more.",
      "4️⃣ Earn XP & Build Your Streak\n🔥 Practice every day, earn XP, maintain your streak, and keep improving your performance.",
      "5️⃣ Learn From Your Mistakes\n❌ Get questions wrong? No problem. Your Mistake Bank helps you review the questions you struggled with and turn mistakes into progress. 💪",
      "6️⃣ Free vs Pro\n🆓 Free: Up to 20 questions per day with access to core features.\n💎 Pro: Unlimited practice, Mistake Bank, every track, and the full Pro experience.\n\n🏆 Study. Compete. Improve. Ace Your Matric. 🎯",
    ],
    supportTitle: "🛠️ NEED HELP? WE’VE GOT YOU!",
    supportBody:
      "Having an issue with Pro, payments, your account, or the app? ⭐️📱\nFound a bug or something that doesn’t look right? 🐛\n\n💬 Message our support team on Telegram using the button below.",
    supportOpen: "Message on Telegram",
  },
  am: {
    brand: "የመውጫ ፈተና ዝግጅት",
    selam: "ሰላም",
    student: "ተማሪ",
    home: "መነሻ",
    practice: "ልምምድ",
    exams: "ልምምድ",
    history: "መዝገብ",
    pro: "ፕሮ",
    account: "መገለጫ",
    continueMock: "ፈተና ቀጥል",
    quickDrill: "ፈጣን 10",
    sourcePick: "ጥያቄዎቹ ከየት ይምጡ?",
    sourceMock: "ሞዴል ፈተና",
    sourceMockHint: "ከዩኒቨርሲቲዎች የተሰበሰቡ ሞዴሎች",
    sourceMockCount: "ከዩኒቨርሲቲ ሞዴሎች {n} ጥያቄዎች",
    sourceMockEmpty: "ለዚህ ክፍል ሞክ ፈተና የለም",
    sourcePast: "ያለፉ ፈተናዎች",
    sourcePastHint: "{n} ብሔራዊ ወረቀቶች · ዓመት ይምረጡ",
    sourcePastEmpty: "ለዚህ ክፍል ያለፈ የመውጫ ፈተና የለም",
    sourcePastKicker: "ያለፉ የመውጫ ፈተናዎች",
    sourcePastTitle: "ዓመት ይምረጡ",
    sourcePastBody: "ብሔራዊ ወረቀቶች፣ በዓመት የተሰየሙ። ያንን ፈተና ይቀመጣሉ።",
    sourceBlurbQuick: "የጥያቄ ምንጭ ይምረጡ። አስር ጥያቄ፣ ሰዓት የለም — ሲጨርሱ።",
    sourceBlurbExam: "ሞክ ፈተና የዩኒቨርሲቲ ሞዴሎች ናቸው። ያለፉ የመውጫ ፈተናዎች ብሔራዊ ወረቀቶች ናቸው።",
    questionBank: "ጥያቄ ባንክ",
    sourceMockSub: "የዩኒቨርሲቲ ሞዴሎች",
    sourcePastSub: "ብሔራዊ ወረቀቶች",
    sourceAll: "ሁሉ በዘፈቀደ",
    sourceAllHint: "ሞክ እና ያለፉ ፈተናዎች ተደምድሞ",
    sourceAllCount: "ከሁሉም ወረቀቶች {n} ጥያቄዎች",
    sourceAllEmpty: "ለዚህ ክፍል ጥያቄ የለም",
    sourceNeedPick: "መጀመሪያ ሞክ ፈተና ወይም ያለፈ የመውጫ ፈተና ይምረጡ",
    countPickKicker: "የጥያቄ ብዛት",
    countPickTitle: "ስንት ጥያቄ?",
    countPickBody: "ብዛት ይምረጡ። ሙሉ ወረቀቱን በአንድ ጊዜ አይቀመጡም።",
    countPickGoal: "የዕለቱ ግብዎ",
    countPickQs: "{n} ጥያቄዎች",
    countPickTime: "ወደ {n} ደቂቃ",
    countPickTooFew: "ይህ ወረቀት {n} ጥያቄ አለው",
    countPickAll: "በዚህ ወረቀት ያሉት {n} በሙሉ",
    practiceMockHint: "{n} የዩኒቨርሲቲ ሞዴል ጥያቄዎች",
    tracks: "ትምህርት ክፍሎች",
    pickTrack: "ትምህርት ክፍልዎን ይምረጡ",
    trackLocked: "በነፃ እቅድ ላይ ክፍል መቀየር አይቻልም።",
    changeTrackPro: "በፕሮ ይቀይሩ",
    streak: "ተከታታይ",
    xp: "ነጥብ",
    free: "ነጻ",
    proActive: "ፕሮ ንቁ ነው",
    upgrade: "ወደ ፕሮ ይቀይሩ",
    onboardingTitle: "መጀመሪያ ማስጀመር",
    language: "ቋንቋ",
    theme: "ገጽታ",
    accent: "ቀለም",
    fontSize: "የጽሁፍ መጠን",
    dailyGoal: "ዕለታዊ ጥያቄ ግብ",
    haptics: "ንዝረት",
    sound: "ድምጽ",
    instant: "ወዲያው መልስ",
    motion: "እንቅስቃሴ ቀንስ",
    university: "ዩኒቨርሲቲ",
    year: "የትምህርት ዓመት",
    examYear: "የፈተና ዓመት",
    save: "አስቀምጥ",
    next: "ቀጣይ",
    finish: "ጀምር",
    noQuestions: "እስካሁን የታተመ ጥያቄ የለም።",
    review: "መልስ ግምገማ",
    backHome: "መነሻ",
    score: "ውጤትዎ",
    pending: "የአስተዳዳሪ ግምገማ በመጠባበቅ ላይ",
    rejected: "ክፍያው ተቀባይነት አላገኘም",
    submitPay: "ለማጽደቅ ላክ",
    hallOfFame: "ከፍተኛ ውጤት",
    scoreboard: "ደረጃ",
    boardBlurbBiweekly: "የዚህ ሁለት ሳምንት አሸናፚዎች በ {track}።",
    boardBlurbMonthly: "የዚህ ወር አሸናፚዎች በ {track}።",
    boardBlurbAll: "የዘመን ደረጃ በ {track}።",
    periodBiweekly: "2 ሳምንት",
    periodMonthly: "ወር",
    periodAllTime: "ሁሉም ጊዜ",
    yourStanding: "ደረጃዎ",
    changeTrack: "ክፍል",
    yourTrack: "ክፍልዎ",
    noPeriodPlayers: "በዚህ ጊዜ ውጤት የለም።",
    noPlayers: "ለዚህ ክፍል እስካሁን ተጋዋች የለም።",
    unrankedPeriod: "በዚህ ጊዜ ደረጃ የለዎትም",
    timeUp: "ጊዜ አልቋል",
    pencilsDown: "ጊዜው አልቋል",
    timeUpBody:
      "ሰዓቱ ያለቀ። ያስቀመጡት መልሶች ተቆጥረዋል። ባዶ ጥያቄዎች ተሳስተው ይቆጠራሉ።",
    seeResults: "ውጤት ይመልከቱ",
    posting: "ውጤት በመላክ ላይ…",
    seeMore: "ተጨማሪ ይመልከቱ",
    showMore: "ተጨማሪ አሳይ",
    redeemKicker: "ስጦታ አለህ?",
    redeemTitle: "ኮድ ተቀበል",
    redeemHint: "የፕሮ ስጦታ ኮድ ያስገቡ።",
    redeemPlaceholder: "የስጦታ ኮድ",
    redeemAction: "ተቀበል",
    redeemEmpty: "የስጦታ ኮድ ያስገቡ።",
    redeemSuccess: "ስጦታው ተቀብሏል። ፕሮ ንቁ ነው።",
    redeemFailed: "መቀበል አልተሳካም።",
    redeemAlreadyPro: "ፕሮ አለዎት።",
    redeemNotFound: "የስጦታ ኮድ አልተገኘም።",
    redeemOwnGift: "የራስዎን ስጦታ መቀበል አይችሉም።",
    redeemPending: "ይህ ስጦታ ግምገማ ላይ ነው።",
    redeemClaimed: "ይህ ስጦታ ቀድሞ ተቀብሏል።",
    redeemInvalid: "ይህ ስጦታ አሁን ዋጋ የለውም።",
    saving: "በመቀመጥ ላይ…",
    homeHudXp: "ነጥብ",
    homeHudLast: "መጨረሻ",
    homeBrand: "MATRIC PREP",
    homeQuick10: "ፈጣን 10",
    homeExam: "ፈተና",
    homeDuel: "ዱኤል",
    homeMistakeBank: "የስህተት ባንክ",
    homeLeaderboard: "ደረጃ",
    homeReview: "መልስ ግምገማ",
    homePractice: "ጥያቄ ባንክ",
    homeNotes: "ማስታወሻ",
    homeSubNotes: "የጥናት ማስታወሻ ያንብቡ",
    notesKicker: "ማስታወሻ",
    notesTitle: "የጥናት ማስታወሻ",
    notesComingSoon: "በቅርብ ይመጣል። ለሁሉም ክፍሎች ማስታወሻ እንጨምራለን።",
    notesSoonBadge: "በቅርብ",
    homeSub10NoTimer: "10 ጥያቄ · ሰዓት የለውም",
    homeSubTimed: "{n} ጥያቄ · timed",
    homeSubDuelFriends: "ከጓደኞች ጋር ዱኤል",
    homeSubRetryWeak: "ደካሞችን ይመለሱ",
    homeSubRankings: "ደረጃዎች",
    homeSubLastScore: "መጨረሻ {n}%",
    homeSubNoSitting: "እስካሁን ፈተና የለም",
    homeSubBrowseBank: "ጥያቄዎችን ይምረጡ",
    homeDailyLimit: "ገደብ ሞሏል",
    homeCreditPro: "ክሬዲት ∞",
    homeCreditFree: "ክሬዲት {left}/20",
    homeUpgradeHint: "የቀን ገደብ ሞሏል — ያልተገደበ ለፕሮ ያሳድጉ",
    restrictClose: "በኋላ",
    restrictUpgrade: "ፕሮ ይቀይሩ",
    restrictPerk1: "ያልተገደበ ጥያቄ እና 100 ጥያቄ ፈተና",
    restrictPerk2: "ዱኤል: 2–10 ተጫዋቾች፣ እስከ 100 ጥያቄ",
    restrictPerk3: "የስህተት ባንክ ታሪክ እና ልምምድ",
    restrictPerk4: "ሁሉም ክፍሎች እና ብሉፕሪንት",
    restrictPerk5: "አንድ ክፍያ (200 ብር) · እስከ ወቅት መጨረሻ",
    restrictQuestionsKicker: "ነፃ ገደብ ሞሏል",
    restrictQuestionsTitle: "20 / 20 ጥያቄ",
    restrictQuestionsBadge: "የቀን ገደብ",
    restrictQuestionsDesc:
      "ነፃ መለያዎች ቀን በቀን 20 ጥያቄ ያገኛሉ። ፕሮ ሙሉ 100 ጥያቄ ፈተና እና ያልተገደበ ልምምድ ይከፍታል።",
    restrictDuelsKicker: "ነፃ ገደብ ሞሏል",
    restrictDuelsTitle: "20 / 20 ጥያቄ",
    restrictDuelsBadge: "የቀን ገደብ",
    restrictDuelsDesc:
      "ዱኤል ጥያቄዎች ከፈተና ጋር ተመሳሳይ 20 ጥያቄ ገደብ ይጠቀማሉ። ፕሮ እስከ 10 ተጫዋቾች ይደግፋል።",
    restrictMistakesKicker: "ፕሮ መደብር",
    restrictMistakesTitle: "የስህተት ባንክ ተቆልፏል",
    restrictMistakesBadge: "የፕሮ ባህሪ",
    restrictMistakesDesc:
      "የተሳሳቱ ጥያቄዎችን መመለስ እና ደካሞችን መለማመድ ለፕሮ ተጠቃሚዎች ነው። ድጋግመው መለማመድ ወደ 70%+ ያስፋፋል።",
    restrictProStageKicker: "ፈተና ተቆልፏል",
    restrictProStageTitle: "የፕሮ ፈተና",
    restrictProStageBadge: "ፕሮ ያስፈልጋል",
    restrictProStageDesc:
      "ይህ ብሔራዊ ፈተና ለፕሮ ብቻ ነው። ሁሉንም ዓመታት እና ብሉፕሪንት ይክፈቱ።",
    restrictGeneralKicker: "ፕሮ ይክፈቱ",
    restrictGeneralTitle: "ያልተገደበ ልምምድ",
    restrictGeneralBadge: "የወቅት ፓስ",
    restrictGeneralDesc:
      "ያልተገደበ ጥያቄ፣ የስህተት ልምምድ እና ዱኤል በፕሮ ይገኛሉ።",
    homeSelectMode: "ሁነታ ይምረጡ",
    homeReady: "ዝግጁ",
    homeStatsKicker: "ውጤት",
    homeStatsStreakBadge: "{n} ቀን ተከታታይ",
    homeStatsStreak: "ተከታታይ",
    homeStatsDays: "ቀናት",
    homeStatsGoal: "ግብ",
    homeStatsScore: "ነጥብ",
    homeStatsRecent: "የቅርብ ፈተናዎች",
    homeStatsAria: "የተማሪ ስታት",
    homeStreakTooltip: "{n} ቀን ተከታታይ",
    homeCoinOp: "ክሬዲት",
    homeQuotaLeft: "{left} / {max} ጥያቄ ቀርቷል",
    homeQuotaEmpty: "0 ቀርቷል",
    homeQuotaUsed: "ዛሬ {used} ከ {max} ጥያቄ ተጠቅመዋል",
    homeQuotaDetails: "ዝርዝር",
    homeQuotaGoPro: "ፕሮ ይክፈቱ",
    homeQuotaNoActivity: "ዛሬ እንቅስቃሴ የለም",
    homeQuotaUsedSummary: "ተጠቅሟል: {summary}",
    homeMarqueePro: "★ ፕሮ ንቁ ★",
    homeMarqueeCoin: "★ ፕሮ ይክፈቱ ★",
    homeMarqueeQuestions: "{n} ጥያቄ",
    homeMarqueeRun: "{duration} ሮድ",
    homeMarqueeStreak: "ተከታታይ {n} ቀናት",
    homeMarqueeLuck: "መልካም እድል {name}",
    homeDurationHours: "{h} ሰ",
    homeDurationHoursMin: "{h} ሰ {m} ደ",
    homeDurationMin: "{m} ደቂቃ",
    proPageKicker: "ፕሮ",
    proInsertCoin: "ፕሮ ይክፈቱ",
    proOnePayment: "አንድ ክፍያ እስከ የመውጫ ፈተና ወቅት መጨረሻ ይሸፍንዎታል።",
    proSeasonEndsOn: "ፕሮ እስከ {date} — የመውጫ ፈተና ወቅት መጨረሻ ይቆያል።",
    proPayMethodLabel: "የክፍያ መንገድ ይምረጡ",
    proPayTapToSelect: "ቁጥሩን ለማየት የክፍያ መንገድ ይምረጡ",
    proCopyNumber: "ቁጥር ቅዳ",
    proNumberCopied: "ቁጥሩ ተቀድቷል",
    proCheckoutPerk1: "ሁሉም ክፍሎች",
    proCheckoutPerk2: "ያልተገደበ ፈተና",
    proCheckoutPerk3: "የስህተት ባንክ ልምምድ",
    proCheckoutPerk4: "ዱኤል (2–10 ተጫዋቾች)",
    proCheckoutPerk5: "ብሉፕሪንት ክብደቶች",
    proCheckoutPerk6: "የመልስ ግምገማ ለዘለዓለም",
    proPaymentHeading: "ክፍያ",
    proScreenshotLabel: "ስክሪንሻት",
    proProcessing: "በሂደት ላይ",
    proAttachScreenshot: "የክፍያ ስክሪንሻት ያያዩ።",
    proImageOnly: "ምስል (ስክሪንሻት ወይም ፎቶ) ይስቀሉ።",
    proImageMaxSize: "ምስሉ በጣም ትልቅ ነው (ከፍተኛ 5 MB)።",
    proUploadFailedMsg: "መላክ አልተሳካም። እንደገና ይሞክሩ።",
    proSubmittedAdmin: "ተላክቷል። አስተዳዳሪ ይገመግማል።",
    proAccessUnlocked: "ፕሮ ተከፍቷል",
    proUntilDate: "እስከ {date}",
    proSeasonEndFallback: "የወቅት መጨረሻ",
    proMemberDesc: "ገደብ የለውም። ሙሉ ፈተና እና ዱኤል ዝግጁ ናቸው።",
    proGiftKicker: "ፕሮ ስጦታ",
    proGiftTitle: "ለጓደኛ ስጦታ",
    proGiftAttach: "የክፍያ ስክሪንሻት ያያዩ።",
    proGiftSubmitted: "ተላክቷል። ኮዱ ከግምገማ በኋላ ይከፈታል።",
    proGiftPayCopy: "{price} ብር ይክፈሉ። ከግምገማ በኋላ ኮድ ይደርስዎታል።",
    proGiftOpenCode: "ክፍት ኮድ",
    proGiftCopied: "ተቀድቷል",
    proGiftCopyBtn: "ቅዳ",
    proGiftSendBtn: "ላክ",
    proGiftSubmitBtn: "ፕሮ ስጦታ · {price} ብር",
    proGiftReviewWait: "ክፍያ በግምገማ ላይ። ከተጸድቀ ኮዱ ይከፈታል።",
    proGiftClaimedBy: "{code} በ {name} ተቀብሏል",
    proUploadFailed: "መላክ አልተሳካም",
    proBenefitsSr: "የፕሮ ጥቅሞች",
    proStatusSr: "የፕሮ ሁኔታ",
    proHeroExamTitle: "ፈተና",
    proHeroExamKicker: "100 ጥያቄ",
    proHeroExamSub: "ከሞክ ወይም ከያለፈ ብሔራዊ ፈተና — timed ፈተና",
    proHeroExamCta: "ፈተና ጀምር",
    proHeroQuickTitle: "ፈጣን 10",
    proHeroQuickKicker: "ፈጣን ሮድ",
    proHeroQuickSub: "10 ጥያቄ በማንኛውም ጊዜ",
    proHeroQuickCta: "ልምምድ",
    proHeroMistakesTitle: "የስህተት ባንክ",
    proHeroMistakesKicker: "ፕሮ መደብር",
    proHeroMistakesSub: "የተሳሳቱ ጥያቄዎችን እስኪሰማሩ",
    proHeroMistakesCta: "ልምምድ",
    proHeroDuelTitle: "ዱኤል",
    proHeroDuelKicker: "ቀጥተኛ ፉክ",
    proHeroDuelSub: "ያልተገደበ ዱኤል ከ2–10 ተጫዋቾች",
    proHeroDuelCta: "ግጥმት",
    howItWorksTitle: "እንዴት ይሰራል?",
    howItWorksSteps: [
      "1️⃣ መጀመሪያ ሲመዘገቡ ክፍልዎን ይምረጡ። በነፃ እቅድ ክፍሉ ይቆለፋል፤ ፕሮ በማንኛውም ጊዜ መቀየር ይችላሉ።",
      "2️⃣ ልምምድ፡ ፈጣን 10 አስር ጥያቄ ነው፣ ሰዓት የለውም። የመውጫ ፈተና ሙሉ timed ፈተና ነው — ከዩኒቨሲቲ ሞዴሎች ወይም ከያለፉ ብሔራዊ ፈተናዎች።",
      "3️⃣ ጥያቄዎችን በመመለስ XP እና ዕለታዊ ተከታታይ ይገኙ። በቴሌግራም ቻትም የዕለቱ ጥያቄ አለ።",
      "4️⃣ ታሪክ የעבר ፈተናዎችን እና መልስ ግምገማን ያሳይዎታል። ፕሮ የስህተት ባንክን ይጨምራል — የተሳሳቱ ጥያቄዎችን እንደገና።",
      "5️⃣ በደረጃ ሰሌዳ ደረጃዎን ይመልከቱ። ዱኤል በመተግበሪያው ከጓደኞች ጋር (2–10 ተጫዋቾች) ይወዳደሩ።",
      "6️⃣ ነፃ፡ ቀን በቀን 20 ጥያቄ። ፕሮ፡ ያልተገደበ ልምምድ፣ ሁሉም ክፍሎች፣ የስህተት ባንክ እና ዱኤል እስከ የፈተና ወቅት መጨረሻ።",
    ],
    supportTitle: "እገዛ",
    supportBody:
      "ስለ ፕሮ፣ ክፍያ፣ መገለጫዎ ወይም ችግር ያለዎት? በቴሌግራም ይጻፉልን — በተቻለ ፍጥነት እንረዳዎታለን።",
    supportOpen: "በቴሌግራም ይጻፉ",
  },
} as const;

/**
 * User-facing copy is split across per-area modules so new screens can add
 * strings without editing this file. Everything is merged here, which is also
 * what the admin translations catalog reads (see lib/i18n/catalog.ts).
 */
export const copy = {
  en: {
    ...baseCopy.en,
    ...shellCopy.en,
    ...onboardingCopy.en,
    ...homeCopy.en,
    ...examCopy.en,
    ...duelCopy.en,
    ...progressCopy.en,
    ...proCopy.en,
    ...marksCopy.en,
  },
  am: {
    ...baseCopy.am,
    ...shellCopy.am,
    ...onboardingCopy.am,
    ...homeCopy.am,
    ...examCopy.am,
    ...duelCopy.am,
    ...progressCopy.am,
    ...proCopy.am,
    ...marksCopy.am,
  },
};

export const SUPPORT_TELEGRAM_URL = "https://t.me/MatricPrepSupport";

export type Lang = keyof typeof copy;
export type AppCopy = (typeof copy)[Lang];
